---
abstract: 'Send passive checks to Nagios locally and remotely.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Class: 0.33
  Test::Most: 0
  Test::Requires: 0.02
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-NSCA-Client
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Convert::Binary::C: 0.74
  Crypt::Random: 0
  Data::Validate::Domain: 0.02
  Digest::CRC: 0
  English: 0
  IO::Socket::INET: 0
  Moose: 0.89
  MooseX::Clone: 0
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.08
  Readonly: 1.03
  namespace::clean: 0.04
  perl: 5.8.1
resources:
  homepage: http://github.com/dougwilson/perl5-net-nsca-client/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-net-nsca-client.git
version: 0.002
